version: '3.1'

services:

  rabbitmq:
    image: rabbitmq:management
    deploy:
        restart_policy:
            condition: always
    ports:
      - "15672:15672"
      - "5672:5672"
    #volumes:
    #- /var/lib/docker/volumes/blockbusterVolume/_data/mongo:/data/db
    environment:
      RABBITMQ_DEFAULT_USER: root
      RABBITMQ_DEFAULT_PASS: example
